### ISSUE TITLE
Links unter "Mehr Informationen" sollten immer in einem neuen Tab aufgehen

### ISSUE THREAD

**Issue by fleaz** [wahlbilanz/WahlBerater#1]
Hey,

die Links unter "Mehr Informationen" haben aber leider kein target="_blank" weswegen sie im gleichen Tab geöffnet werden. Dadurch verliert man den Fortschritt im Quiz und muss sich falls man noch andere Links angeklickt hat, mehrmals durch die Browserhistory klicken bis man wieder beim Quiz  ist und dann auch wieder von vorne starten.

Felix

**Comment by tomthe** [comment]
Ja stimmt, neuer Tab wäre meiner Meinung nach auch besser. Allerdings sollte der Fortschritt beim Zurückgehen über den Zurück-Button normalerweise erhalten bleiben.

**Comment by binfalse** [comment]
danke fuer die idee! fixed :)
