### ISSUE TITLE
Schrägstrich in Parteiname wird nicht escaped

### ISSUE THREAD

**Issue by mgmax** [wahlbilanz/WahlBerater#2]
Wenn ich im Balkendiagramm https://btw21.deinwal.de/quiz/result auf CDU/CSU klicke,
funktioniert der Link `https://btw21.deinwal.de/parties/CDU/CSU` nicht.
```
ERROR Error: Uncaught (in promise): Error: Cannot match any routes. URL Segment: 'parties/CDU/CSU'
```

Auf "Parteien" https://btw21.deinwal.de/parties funktioniert es hingegen korrekt, dort zeigt der Link auf
`https://btw21.deinwal.de/parties/CDU%2FCSU`.

Das Problem ist also wohl der Schrägstrich.

**Comment by binfalse** [comment]
ist uebrigens gefixt! danke fuer den hinweis! :)
